---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: minikube-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-training
      component: mysql
  template:
    metadata:
      name: mysql-pod
      namespace: minikube-training
      labels:
        app: minikube-training
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: user
        - name: MYSQL_DATABASE
          value: minikube_training
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
            