---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: minikube-training
spec:
  selector:
    app: minikube-training
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: NodePort