version: "3.5"

services:
  nginx:
    environment:
      BACKEND: php-dev
    volumes:
      - "./.docker/nginx/minikube.training.nginx.conf:/etc/nginx/conf.d/default.conf.template"
      - "./:/var/www/minikube.training:cached"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  php-dev:
    build:
      dockerfile: .docker/php-dev/Dockerfile
      context: .
    image: enalquilertrainings/minikube-training-php:dev
    volumes:
      - "./:/var/www/minikube.training:cached"
    depends_on:
      - php
volumes:
  mysql: