---
apiVersion: batch/v1
kind: Job
metadata:
  name: database-fixtures
  namespace: minikube-training
  labels:
    app: minikube-training
    env: prod
spec:
  template:
    metadata:
      namespace: minikube-training
      labels:
        app: minikube-training
        env: prod
    spec:
      containers:
      - name: database-fixtures
        image: enalquilertrainings/minikube-training-php:cli
        imagePullPolicy: Always
        command: ["php", "bin/console", "doc:fixtures:load", "--no-interaction"]
        envFrom:
          - configMapRef:
              name: minikube-training-config
          - secretRef:
              name: minikube-training-secret
      restartPolicy: Never
      imagePullSecrets:
      - name: enalquiler-registry