---
apiVersion: batch/v1
kind: Job
metadata:
  name: minikube-training-migrations
  labels:
    app.kubernetes.io/name: minikube.training
    app: minikube-training-cli
    env: prod
spec:
  template:
    spec:
      containers:
      - name: cli-migrations
        image: enalquilertrainings/minikube-training-php:cli
        imagePullPolicy: Always
        command: ["php",  "bin/console", "doc:mig:m", "--no-interaction"]
        env:
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_env
          - name: APP_DEBUG
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_debug
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_secret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: database_url
          - name: MAILER_URL
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: mailer_url
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minikube-training-fixtures
  labels:
    app.kubernetes.io/name: minikube.training
    app: minikube-training-cli
    env: prod
spec:
  template:
    spec:
      containers:
      - name: cli-fixtures
        image: enalquilertrainings/minikube-training-php:cli
        imagePullPolicy: Always
        command: ["php",  "bin/console", "doc:fixtures:load", "--no-interaction"]
        env:
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_env
          - name: APP_DEBUG
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_debug
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: app_secret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: database_url
          - name: MAILER_URL
            valueFrom:
              secretKeyRef:
                name: minikube-training-production-cli-params
                key: mailer_url
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 4