---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: minikube.training
    env: prod
spec:
  containers:
    - image: hello-world
      name: hello-world-from-yaml
  restartPolicy: Never