---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-training-database-pv
  namespace: minikube-training
  labels:
    volume: minikube-training-database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/lib/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minikube-training-database-pvc
  namespace: minikube-training
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      volume: minikube-training-database-pv