---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: minikube-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-training
      component: mta
  template:
    metadata:
      namespace: minikube-training
      labels:
        app: minikube-training
        component: mta
    spec:
      containers:
        - image: mailhog/mailhog
          name: mailhog
          ports:
          - containerPort: 1025
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: minikube-training
  labels:
    app: minikube-training
spec:
  selector:
    app: minikube-training
    component: mta
  ports:
  - protocol: TCP
    port: 1025
    targetPort: 1025