---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: minikube-training
  labels:
    app: minikube-training
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-training
      component: webserver
      env: prod
  template:
    metadata:
      namespace: minikube-training
      labels:
        app: minikube-training
        component: webserver
        env: prod
    spec:
      containers:
      - image: enalquilertrainings/minikube-training-nginx
        imagePullPolicy: Always
        name: minikube-training-nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: BACKEND
          value: php
      imagePullSecrets:
      - name: enalquiler-registry
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: minikube-training
  labels:
    app: minikube-training
    env: prod
spec:
  selector:
    app: minikube-training
    component: webserver
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80